services:
  mysql:
    image: mysql:8.4
    container_name: ${APP_NAME}-mysql
    ports:
      - "33061:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-time-zone=+08:00",
        "--mysql_native_password=ON",
      ]

  # redis:
  #   image: redis:7
  #   container_name: my-leran-redis
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "7"
  #   ports:
  #     - "16379:16379"
  #   volumes:
  #     - ./db/redis:/data
  #   restart: always
  #   command: redis-server --port 16379 --requirepass ${REDIS_PASSWORD}
